### ISSUE TITLE
Document max rev tree depth ramifications with 1.3.0 autocompaction

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/couchbase-mobile-portal#341]
As of 1.3.0, the Lite clients will auto compact the number of revs to a max depth. This can cause conflicts in certain scenarios during replication. For instance, if a client goes offline and update enough times to have a common ancestor deleted, when it replicates with sync_gateway after coming back online, it will create a new open revision. This can lead to some unexpected behavior. 

@snej If you can comment on other scenarios to be aware of / tuning, best practices, that would be helpful.

**Comment by jamiltz** [comment]
Since it's supported on all storage types in 1.3 we could add a paragraph in database housekeeping http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/native-api/database/index.html#database-housekeeping

This paragraph already mentions the following with regards to max rev tree depth:

> Setting this to a smaller value will save storage space, but can result in spurious conflicts if users are making lots of offline changes and then sync.

Is there an expected behaviour we can write about for conflicts of the same doc with out a common ancestor?

I will add a paragraph in 1.3 docs to point out that it's done automatically and calling `.compact` is not needed.
