### ISSUE TITLE
Back-port: wildcard in logrotate examples results in repeated rotation

### ISSUE THREAD

**Issue by malarky** [couchbaselabs/couchbase-mobile-portal#494]
From the logrotate manual:

> Please  use  wildcards  with caution.  If you specify *, logrotate will rotate all files, including previously rotated ones.  A way around this is  to  use  the  olddir  directive  or  a more exact wildcard (such as *.log).

Basically, you end up rotating `error.log` to `error.log.1`, which is then rotated to `error.log.1.1`.

**Comment by malarky** [comment]
Also affects 1.1.x but don't know which branch that is.

**Comment by jamiltz** [comment]
We're transitioning to having all versions of the documentation on master rather than on each branch. The [`_1x`](https://github.com/couchbaselabs/couchbase-mobile-portal/tree/dev/md-docs/_1x) folder has the content relevant to 1.1, 1.2, 1.3 and soon 1.4. Once we finalise this process, we'll be able to update the 1.1 docs with the fix.

Renaming this ticket and moving it to the backlog.

**Comment by jamiltz** [comment]
content changed in
