### ISSUE TITLE
Improve documentation about Local Docs

### ISSUE THREAD

**Issue by malarky** [couchbaselabs/couchbase-mobile-portal#502]
Please add an introductory paragraph on  Local Docs (what they are, how to use them, limitations on Views/Sync).

**Comment by benjaminglatzeder** [comment]
@malarky opened this issue because I used the Local Docs incorrectly.

I created/received/deleted Local Docs in Android like so:
```
database.getDocument("_local/" + "<document name>"); // INCORRECT create statement
database.getDocument("_local/" + "<document name>"); // INCORRECT get statement
database.getDocument("<document name>").delete(); // INCORRECT delete statement
```
CBL tried to sync theses documents and SG rejected them. I'm aware that Local Docs cannot be synced. I thought it was a bug in CBL 1.3.1 because CBL tried to sync them.

I also tried to query these types of documents with a View which worked in testing but in production it returned wrong results for users.
