### ISSUE TITLE
Lots of broken links

### ISSUE THREAD

**Issue by mattcarabine** [couchbaselabs/couchbase-mobile-portal#510]
After our conversation the other day, I ran [linkchecker](https://github.com/wummel/linkchecker) against the mobile docs and found tonnes of link errors:

https://gist.github.com/jamiltz/e9cd82fde2bb88d54025b03effe04b69

I want to add this link checking to our automation, I have already done so for server after fixing a few latent issues. The first step to doing this for mobile is to clear up these issues.

This link checking took a little bit of setting up to get working well, so let me know if you need any more info!

**Comment by jamiltz** [comment]
Most of the errors are related to images. Let's take the first one for example

```
URL        `img/wpf-nuget.png'
Parent URL file:///var/lib/jenkins/docs_mobile_master_output/installation/net/index.html, line 225, col 1
Real URL   file:///var/lib/jenkins/docs_mobile_master_output/installation/net/img/wpf-nuget.png
Check time 0.004 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/var/lib/jenkins/docs_mobile_master_output/installation/net/img/wpf-nuget.png'>
```

Jekyll outputs the following.

![image](https://cloud.githubusercontent.com/assets/2589337/21096817/4dc0ee74-c059-11e6-85c6-69cf9ba83af3.png)

**net/index.html** expects the image to be at **img/wpf-nuget.png** relatively but in fact it's at **../img/wpf-nuget.png**.

After ingestion however, the image is displayed correctly http://developer.couchbase.com/documentation/mobile/1.3/installation/net/index.html. I think that the ingestion process looks for all `<img src="..." />` and moves the images to the root.

It is convenient because images show in the github preview https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/md-docs/ready/installation/net.md

If we fix those broken links, the image won't show in the github ui anymore ([like this](https://github.com/facebook/react/blob/master/docs/tutorial/tutorial.md#passing-data-through-props)) because of the way jekyll outputs the docs.

Fortunately this works because of the way the ingestion process handles images but I've not found a solution with Jekyll that correctly links images on the github ui while having valid links in the html output. Both are important. But to fix the broken links is probably more important so that we can use that link checker tool going forward. Let's keep this issue open until I move things around (**img** directories).

**Comment by jamiltz** [comment]
Thanks for your feedback and help to improve the docs! We've moved the ticket to [https://issues.couchbase.com/browse/DOC-2886](https://issues.couchbase.com/browse/DOC-2886) and will get it fixed as soon as possible.
