### ISSUE TITLE
add prev/next buttons in tutorial jekyll theme

### ISSUE THREAD

**Issue by mattcarabine** [couchbaselabs/couchbase-mobile-portal#725]
From https://issues.couchbase.com/browse/DOC-2480

---

Any reason for not having <Previous and Next> buttons on this tutorial page. Progressively navigating through the tutorial is onerous having to go to the left nav all the time to move to the next it.

**Comment by jamiltz** [comment]
@asifkazi I think that tutorial type content shouldn't be in the docs in the first place. Working on moving the tutorial to a standalone location similar to http://docs.couchbase.com/tutorials/travel-sample-mobile.html. So I'll rename this ticket to add the next/prev button to the jekyll theme instead of the docs.

**Comment by jamiltz** [comment]
As the theme is used for server/mobile sample/tutorials now, I'll close this issue here and work with PM directly to see when it can be added to the theme in the `couchbaselabs/docs-style-guide` repo.
