### ISSUE TITLE
users property not documented

### ISSUE THREAD

**Issue by djpongh** [couchbaselabs/couchbase-mobile-portal#740]
The "users" property is not documented on  https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/config-properties/index.html

**Comment by jamiltz** [comment]
The `users` property takes users as value. So the [foo user](https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/config-properties/index.html#foo_user) is documented. The fact that the user name is the key makes it a bit harder to document. I don't know how to document the `users` property because it really is just a container for user objects.

**Comment by jamiltz** [comment]
fixed.
